### ISSUE TITLE
Last updated date and Last Update By getting updated for few of the previously completed assessments

### ISSUE THREAD

**Issue by saritabarve** [openanthem/nimbus-core#552] opened 2019-07-12 18:09 UTC
Last updated date and Last Update By getting updated for few of the previously completed assessments

**Comment by lopezton-anthem** [comment] 2019-07-12 19:26
This is likely a duplicate of #535. Please review and follow up.

**Comment by lopezton-anthem** [comment] 2019-07-15 20:56
I spoke with the team on this and asked them to investigate if any `setState` methods were being invoked on the core, similar to what was suggested for #535.

**Closed** 2019-07-18 14:10 UTC
Labels: Open, configuration error, duplicate, meeting-required
